name: Check
on: [push, pull_request, workflow_dispatch]
jobs:
  checks:
    name: Check expressions on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64-linux]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - uses: cachix/install-nix-action@v30
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true# NixOS
            environment.systemPackages = [
              inputs.nixvim.packages.${pkgs.system}.default
            ];

            # OR home-manager
            home.packages = [
              inputs.nixvim.packages.${pkgs.system}.default
            ];
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            system = ${{ matrix.arch }}
      - name: run flake check
        run: nix flake check --system ${{ matrix.arch }}
